image: "ruby:2.5"
stages:
 - patch
 - package

variables:
  ORIGIN: https://github.com/chef/chef.git

Cinc-patch:
  stage: patch
  script:
    - git clone --depth=1 $ORIGIN
    - apt-get update
    - apt-get install -y rename
    - cd chef/bin
    - rename 's/chef/cinc/' *
    - cd ../..
    - cp -R cinc/* chef/
    - sed -i '/s.executables  =/ s/chef/cinc/g' chef/chef.gemspec
    - ls chef/*
  artifacts:
    expire_in: 1d
    paths:
      - chef/
  
Cinc-package-deb:
  when: manual
  stage: package
  script:
    - apt-get update 
    - apt-get -y install git build-essential
    - gem install omnibus
    - cd chef/omnibus
    - bundle install --without development
    - bundle exec omnibus build cinc
    - ls -alh */*
    - mv pkg/*.deb $CI_PROJECT_DIR
  artifacts:
    expire_in: 1mo
    paths:
      - ./*.deb

Cinc-package-rpm:
  when: manual
  image: "centos:centos7"
  stage: package
  script:
    - yum -y update 
    - yum -y install git bzip2 which rpmbuild gpg openssl-devel readline-devel zlib-devel autoconf bison flex gcc gcc-c++ gettext kernel-devel make m4 ncurses-devel patch rpm-build rpm-sign
    - export PATH=/usr/local/rvm/gems/ruby-$RUBY_VERSION/bin:/usr/local/rvm/gems/ruby-$RUBY_VERSION@global/bin:/usr/local/rvm/rubies/ruby-$RUBY_VERSION/bin:/usr/local/rvm/bin:$PATH
    - export GEM_HOME=/usr/local/rvm/gems/ruby-$RUBY_VERSION
    - export GEM_PATH=/usr/local/rvm/gems/ruby-$RUBY_VERSION:/usr/local/rvm/gems/ruby-$RUBY_VERSION@global
    - gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    - curl -L get.rvm.io | bash
    - rvm install $RUBY_VERSION
    - yum clean all
    - rvm use $RUBY_VERSION --default
    - gem install bundler -v $(grep :bundler chef/omnibus_overrides.rb | cut -d'"' -f2)
    - ruby -v
    - gem install omnibus
    - cd chef/omnibus
    - bundle install --without development
    - bundle exec omnibus build cinc
    - ls -alh */*
    - mv pkg/*.rpm $CI_PROJECT_DIR
  variables:
    RUBY_VERSION: 2.5.5
  artifacts:
    expire_in: 1mo
    paths:
      - ./*.rpm

Cinc-package-windows:
  image: "mcr.microsoft.com/windows/nanoserver:latest"
  stage: package
  script:
  - dir *      