image: "ruby:2.5"
stages:
 - patch
 - package

variables:
  ORIGIN: https://github.com/chef/chef.git

Cinc-patch:
  stage: patch
  script:
    - git clone --depth=1 $ORIGIN
    - apt-get update
    - apt-get install -y rename
    - cd chef/bin
    - rename 's/chef/cinc/' *
    - cd ../..
    - cp -R cinc/* chef/
    - sed -i '/s.executables  =/ s/chef/cinc/g' chef/chef.gemspec
    - ls chef/*
  artifacts:
    expire_in: 1d
    paths:
      - chef/
  
Cinc-package-deb:
  stage: package
  script:
    - apt-get update 
    - apt-get -y install git build-essential
    - gem install omnibus
    - cd chef/omnibus
    - bundle install --without development
    - bundle exec omnibus build cinc
    - ls -alh */*
    - mv pkg/*.deb $CI_PROJECT_DIR
  when: manual
  artifacts:
    expire_in: 1mo
    paths:
      - ./*.deb

Cinc-package-rpm:
  image: "centos:centos7"
  stage: package
  script:
    - yum -y update 
    - yum -y install git autoconf bison flex gcc gcc-c++ gettext kernel-devel make m4 ncurses-devel patch
    - curl -sSL https://get.rvm.io | bash -s stable --ruby=2.5.5
    - source /usr/local/rvm/scripts/rvm
    - gem install omnibus
    - cd chef/omnibus
    - bundle install --without development
    - bundle exec omnibus build cinc
    - ls -alh */*
    - mv pkg/*.rpm $CI_PROJECT_DIR
  artifacts:
    expire_in: 1mo
    paths:
      - ./*.rpm