image: ccbuild/omnibus-debian
stages:
 - patch
 - package
 - test
 - deploy
 - publish

variables:
  ORIGIN: https://github.com/chef/chef.git

client_patch:
  stage: patch
  tags:
    - osuosl
  script:
    - echo "Cloning from $ORIGIN"
    - git clone --depth=1 $ORIGIN
    - cp -R cinc/* chef/
    - mkdir -p ${CI_PROJECT_DIR}/{cache,cache/git_cache}
    - echo "cache_dir '${CI_PROJECT_DIR}/cache'" >> chef/omnibus/omnibus.rb
    - echo "git_cache_dir '${CI_PROJECT_DIR}/cache/git_cache'" >> chef/omnibus/omnibus.rb
    - sed -i -e 's/^use_git_caching false/use_git_caching true/g' chef/omnibus/omnibus.rb
  artifacts:
    expire_in: 1d
    paths:
      - chef/

.client-package:
  stage: package
  tags:
    - osuosl
  dependencies:
    - client_patch
  script:
    - source /home/omnibus/load-omnibus-toolchain.sh
    - cd chef/omnibus
    - bundle install --without development --path ${CI_PROJECT_DIR}/bundle/vendor
    - bundle exec omnibus build cinc --override append_timestamp:false
    - mkdir ${CI_PROJECT_DIR}/data
    - mv -v pkg/cinc* ${CI_PROJECT_DIR}/data/
  cache:
    paths:
      - cache/*
      - bundle/vendor/*
  artifacts:
    expire_in: 1mo
    paths:
      - data/*

client-package:debian-8:
  extends: .client-package
  image: ccbuild/omnibus-debian:8
  cache:
    key: debian:8
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/debian/8
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/debian/8/

client-package:debian-9:
  extends: .client-package
  image: ccbuild/omnibus-debian:9
  cache:
    key: debian:9
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/debian/9
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/debian/9/

client-package:ubuntu-14.04:
  extends: .client-package
  image: ccbuild/omnibus-ubuntu:14.04
  cache:
    key: ubuntu:14.04
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/ubuntu/14.04
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/ubuntu/14.04/

client-package:ubuntu-16.04:
  extends: .client-package
  image: ccbuild/omnibus-ubuntu:16.04
  cache:
    key: ubuntu:16.04
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/ubuntu/16.04
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/ubuntu/16.04/

client-package:ubuntu-18.04:
  extends: .client-package
  image: ccbuild/omnibus-ubuntu:18.04
  cache:
    key: ubuntu:18.04
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/ubuntu/18.04
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/ubuntu/18.04/

client-package:centos-6:
  extends: .client-package
  image: ccbuild/omnibus-centos:6
  cache:
    key: centos:6
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/centos/6
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/centos/6/

client-package:centos-7:
  extends: .client-package
  image: ccbuild/omnibus-centos:7
  cache:
    key: centos:7
  after_script:
    - mkdir -p ${CI_PROJECT_DIR}/data/centos/7
    - mv -v ${CI_PROJECT_DIR}/data/*.{rpm,deb,json} ${CI_PROJECT_DIR}/data/centos/7/

.client-test:
  stage: test
  tags:
    - osuosl
  script:
    - /opt/cinc/bin/cinc-client --version
    - /opt/cinc/bin/cinc-solo -l info
    - cinc-client --version
    - cinc-solo -l info

client-test:debian-8:
  extends: .client-test
  image: ccbuild/omnibus-debian:8
  dependencies:
    - client-package:debian-8
  before_script:
    - dpkg -i data/debian/8/cinc*.deb

client-test:debian-9:
  extends: .client-test
  image: ccbuild/omnibus-debian:9
  dependencies:
    - client-package:debian-9
  before_script:
    - dpkg -i data/debian/9/cinc*.deb

client-test:ubuntu-14.04:
  extends: .client-test
  image: ccbuild/omnibus-ubuntu:14.04
  dependencies:
    - client-package:ubuntu-14.04
  before_script:
    - dpkg -i data/ubuntu/14.04/cinc*.deb

client-test:ubuntu-16.04:
  extends: .client-test
  image: ccbuild/omnibus-ubuntu:16.04
  dependencies:
    - client-package:ubuntu-16.04
  before_script:
    - dpkg -i data/ubuntu/16.04/cinc*.deb

client-test:ubuntu-18.04:
  extends: .client-test
  image: ccbuild/omnibus-ubuntu:18.04
  dependencies:
    - client-package:ubuntu-18.04
  before_script:
    - dpkg -i data/ubuntu/18.04/cinc*.deb

client-test:centos-6:
  extends: .client-test
  image: ccbuild/omnibus-centos:6
  dependencies:
    - client-package:centos-6
  before_script:
    - yum -y install data/centos/6/cinc*.rpm

client-test:centos-7:
  extends: .client-test
  image: ccbuild/omnibus-centos:7
  dependencies:
    - client-package:centos-7
  before_script:
    - yum -y install data/centos/7/cinc*.rpm

.ssh-setup:
  before_script:
    - eval $(ssh-agent -s)
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

client-deploy:
  when: manual
  stage: deploy
  extends: .ssh-setup
  tags:
    - osuosl
  dependencies:
    - client-package:debian-8
    - client-package:debian-9
    - client-package:ubuntu-14.04
    - client-package:ubuntu-16.04
    - client-package:ubuntu-18.04
    - client-package:centos-6
    - client-package:centos-7
  script:
    - ssh cc-build@${DOWNLOADS_HOST} "mkdir -p /data/incoming/cinc/files/"
    - rsync -avH --delete data/ cc-build@${DOWNLOADS_HOST}:/data/incoming/cinc/files/

client-publish:
  when: manual
  stage: publish
  extends: .ssh-setup
  tags:
    - downloads
  script:
    - rsync -avH /data/incoming/cinc/files/ /data/mirror/cinc/files/
    - ssh -q cc-build@${MIRROR_HOST} "~/sync-from-master"
