platform:
  - x64
  
environment:
  # ORIGIN: https://github.com/chef/chef.git
  ORIGIN: -b dist_solo_zero https://github.com/cc-build/chef.git
  MSYSTEM: mingw64
  OMNIBUS_WINDOWS_ARCH: x64

  matrix:
    - ruby_version: "26-x64"

clone_folder: c:\projects\client
clone_depth: 1

build_script:
  - systeminfo
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem -FileName C:\cacert.pem
  - set SSL_CERT_FILE=C:\cacert.pem
  - ps: . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -project angrychef -v 14
  - git clone -b v5.7.2 https://github.com/chef-cookbooks/omnibus.git
  - /opscode/angrychef/embedded/bin/gem install berkshelf --no-rdoc --no-ri
  - /opscode/angrychef/embedded/bin/berks vendor -b omnibus/Berksfile /chef/cookbooks
  - /opscode/angrychef/bin/chef-solo -o omnibus
  - SET BUNDLE_WITHOUT=server:docgen:pry:integration:ci
  - /omnibus/load-omnibus-toolchain.bat
  - git clone --depth=1 %ORIGIN%
  - xcopy /Y /E /H cinc\* chef\
  - cd chef\omnibus
  - bundle install --without development
  - bundle exec omnibus build cinc
  - dir pkg/*

artifacts:
  - path: pkg\*
  
