platform:
  - x64
  
environment:
  # ORIGIN: https://github.com/chef/chef.git
  ORIGIN: -b dist_solo_zero https://github.com/cc-build/chef.git
  MSYSTEM: mingw64

  matrix:
    - ruby_version: "26-x64"

clone_folder: c:\projects\client
clone_depth: 1

build_script:
  - C:\msys64\usr\bin\bash --login -c "pacman -Sy --noconfirm pacman"
  - C:\msys64\usr\bin\bash --login -c "pacman -Syu --noconfirm"
  - C:\msys64\usr\bin\bash --login -c "pacman -Su --noconfirm"
  - C:\msys64\usr\bin\bash --login -c "pacman -S --needed --noconfirm base"
  - C:\msys64\usr\bin\bash --login -c "pacman -S --needed --noconfirm msys2-devel"
  - C:\msys64\usr\bin\bash --login -c "pacman -S --needed --noconfirm base-devel"
  - C:\msys64\usr\bin\bash --login -c "pacman -S --needed --noconfirm mingw-w64-x86_64-toolchain"
  - C:\msys64\usr\bin\bash --login -c "pacman -S --needed --noconfirm mingw-w64-cross-toolchain"
  - C:\msys64\usr\bin\bash --login -c "pacman -S --needed --noconfirm mingw-w64-i686-toolchain"
  - mklink /J c:\msys2 c:\msys64
  - systeminfo
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - appveyor DownloadFile http://curl.haxx.se/ca/cacert.pem -FileName C:\cacert.pem
  - set SSL_CERT_FILE=C:\cacert.pem
  - SET BUNDLE_WITHOUT=server:docgen:pry:integration:ci
  - git clone --depth=1 %ORIGIN%
  - xcopy /Y /E /H cinc\* chef\
  - cd chef\omnibus
  - bundle install --without development
  - bundle exec omnibus build cinc

artifacts:
  - path: pkg\*.msi